# Indexing

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 첫번째 원소
arr1[0]

0

In [4]:
# 마지막 원소
arr1[-1]

9

In [6]:
# slicing
arr1[:3]

array([0, 1, 2])

In [7]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# arr2의 2, 3 원소
arr2[1,2]

7

In [20]:
# arr2의 세번째 column
arr2[:,2]

array([ 3,  7, 11])

In [16]:
# arr2의 두번째 row
arr2[1]

array([5, 6, 7, 8])

# Masking

In [21]:
mask = np.array([1,0,0,1,1,0,0])

In [22]:
data = np.random.randn(7, 4)
data

array([[ 0.01097981,  0.30823434,  1.43700469,  0.22509563],
       [ 0.29766435, -0.0231893 ,  1.56155928, -0.17463225],
       [-0.1504742 , -0.14722461,  0.59942839, -0.09973447],
       [-0.86422472, -0.10668767, -1.04942774,  1.26385648],
       [ 0.00738826, -1.23681232,  1.14434761,  2.49391939],
       [ 0.44865135,  0.61452   , -1.17877613,  0.72043326],
       [ 1.69260838, -0.61523485,  0.17923746, -0.0381096 ]])

In [23]:
data.shape

(7, 4)

In [24]:
# mask 만들기
masked_data = (mask==1)
masked_data

array([ True, False, False,  True,  True, False, False])

In [25]:
# 위에서 생성한 data에 mask를 적용하기
data[masked_data, :]

array([[ 0.01097981,  0.30823434,  1.43700469,  0.22509563],
       [-0.86422472, -0.10668767, -1.04942774,  1.26385648],
       [ 0.00738826, -1.23681232,  1.14434761,  2.49391939]])

In [26]:
data[mask==0, :]

array([[ 0.29766435, -0.0231893 ,  1.56155928, -0.17463225],
       [-0.1504742 , -0.14722461,  0.59942839, -0.09973447],
       [ 0.44865135,  0.61452   , -1.17877613,  0.72043326],
       [ 1.69260838, -0.61523485,  0.17923746, -0.0381096 ]])

In [27]:
#  fancy indexing을 이용해서 masking
data[data[:, 0]<0, 0]

array([-0.1504742 , -0.86422472])

In [28]:
data[data[:, 0]<0, 0]=0
data

array([[ 0.01097981,  0.30823434,  1.43700469,  0.22509563],
       [ 0.29766435, -0.0231893 ,  1.56155928, -0.17463225],
       [ 0.        , -0.14722461,  0.59942839, -0.09973447],
       [ 0.        , -0.10668767, -1.04942774,  1.26385648],
       [ 0.00738826, -1.23681232,  1.14434761,  2.49391939],
       [ 0.44865135,  0.61452   , -1.17877613,  0.72043326],
       [ 1.69260838, -0.61523485,  0.17923746, -0.0381096 ]])