# Array Operation (like vector)

- numpy array를 쓰는 가장 큰 이유는 vector처럼 사용할 수 있기 때문이다.

- 그렇기 때문에 많은 데이터분석 라이브러리들이 numpy array를 사용한다.

- 데이터 분석은 99.9% 데이터를 벡터로 표현하여 분석하기 때문에, 이 특징은 ***굉장히*** 중요하다.

In [1]:
import numpy as np

In [2]:
# 벡터 생성
v1 = np.array((1,2,3))
v2 = np.array((4,5,6))

In [3]:
# 튜플 더하기 연산
t1 = (1,2,3)
t2 = (4,5,6)

In [4]:
type(v1), type(v2)

(numpy.ndarray, numpy.ndarray)

In [5]:
t1 + t2 # 합쳐진 튜플 생성

(1, 2, 3, 4, 5, 6)

In [6]:
v1 + v2 # 벡터 더하기 연산

array([5, 7, 9])

In [7]:
v1 - v2

array([-3, -3, -3])

In [8]:
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [9]:
# 튜플/리스트는 되고 넘파이 array는 다른 것
l1 = [1,2,3,4]
l2 = [5,6,7]
l1+l2

[1, 2, 3, 4, 5, 6, 7]

In [10]:
np1 = np.array((1,2,3,4))
np2 = np.array((5,6,7))
np1 + np2 
# 브로드캐스팅 에러

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [11]:
# dot product
v1 @ v2

32

# Broadcast

- 서로다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능, 행렬곱 연산을 할 때 편리하다.

In [13]:
arr1 = np.array([[1,2,3,],[4,5,6]])

In [14]:
arr1.shape

(2, 3)

In [15]:
arr2 = np.array([7,8,9])

In [16]:
arr2.shape

(3,)

In [17]:
# 두개의 array를 더해보면??
arr1 + arr2 # [1,2,3] + [7,8,9] // [4,5,6] + [7,8,9] 가 된것!!

array([[ 8, 10, 12],
       [11, 13, 15]])

In [18]:
# 곱해보면??
arr1 * arr2

array([[ 7, 16, 27],
       [28, 40, 54]])

In [19]:
# arr1에 10을 곱해보면??
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
# arr1을 제곱해보면??
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

# Universal Functions

- 하나의 함수를 모든 원소에 자동으로 적용해주는 기능

In [22]:
arr1 = np.array([1,2,3])
arr1 / 1

array([1., 2., 3.])

In [23]:
# 모든 원소를 역수를 취하기
1 /arr1 # 각 원소에 1 나누기라는 operation을 적용한다.

array([1.        , 0.5       , 0.33333333])

In [24]:
# 모든 원소에 2를 더하기
arr1 + 2

array([3, 4, 5])