# Aggregation fuctions

In [1]:
import numpy as np

In [2]:
mat1 = np.random.randn(5,3)

In [3]:
mat1

array([[ 0.84730292,  0.06035716, -1.76164759],
       [-0.09731573,  0.43456578,  0.4736421 ],
       [ 1.01278167,  1.85447988, -0.54835824],
       [ 0.12934362, -1.08690994,  0.12589835],
       [-0.98685908,  1.53962317, -0.15110698]])

In [4]:
np.sum(mat1) # 15개 숫자의 총합.

1.845797083949754

In [5]:
# 다른 축으로 더해보기
np.sum(mat1, axis=1) # row의 총합

array([-0.85398752,  0.81089215,  2.31890331, -0.83166797,  0.40165711])

In [6]:
np.sum(mat1, axis=0) # column의 총합

array([ 0.9052534 ,  2.80211604, -1.86157236])

In [7]:
# 평균
np.mean(mat1)

0.1230531389299836

In [8]:
mat3 = np.random.rand(5, 3)

In [9]:
mat3

array([[0.95766653, 0.90927785, 0.29196464],
       [0.07003891, 0.68757656, 0.52215214],
       [0.24752128, 0.19202592, 0.2980301 ],
       [0.84155795, 0.51785035, 0.96851791],
       [0.24734022, 0.99672754, 0.74793476]])

In [10]:
np.mean(mat3)

0.5664121775908326

In [11]:
np.std(mat3) # 표준편차

0.3143831006500286

In [12]:
np.min(mat1, axis=0)

array([-0.98685908, -1.08690994, -1.76164759])

In [13]:
# 최솟값이 있는 Index
np.argmin(mat3) # 최솟값이 있는 인덱스 반환

3

In [14]:
# 최댓값이 있는 Index
np.argmax(mat3) # 최댓값이 있는 인덱스 반환

13

In [15]:
np.cumsum(mat3) # 누적합

array([0.95766653, 1.86694438, 2.15890902, 2.22894793, 2.91652449,
       3.43867664, 3.68619792, 3.87822384, 4.17625394, 5.01781189,
       5.53566224, 6.50418015, 6.75152037, 7.7482479 , 8.49618266])

In [16]:
np.cumprod(mat3)

array([9.57666529e-01, 8.70784961e-01, 2.54238419e-01, 1.78065829e-02,
       1.22433890e-02, 6.39291181e-03, 1.58238173e-03, 3.03858302e-04,
       9.05589209e-05, 7.62105797e-05, 3.94656756e-05, 3.82232136e-05,
       9.45413800e-06, 9.42319969e-06, 7.04793860e-06])

In [19]:
# 정렬 함수
np.sort(mat3, axis=0)

array([[0.07003891, 0.19202592, 0.29196464],
       [0.24734022, 0.51785035, 0.2980301 ],
       [0.24752128, 0.68757656, 0.52215214],
       [0.84155795, 0.90927785, 0.74793476],
       [0.95766653, 0.99672754, 0.96851791]])

In [20]:
# 인덱스를 정렬
np.argsort(mat3) # argmuent sorting에서 정렬된 값의 원래 위치를 보여줌

array([[2, 1, 0],
       [0, 2, 1],
       [1, 0, 2],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)