# Numpy Methods

In [1]:
import numpy as np

In [2]:
# 랜덤 샘플링 5*3 행렬 만들기
mat1 = np.random.randn(5,3) # 숫자를 파라미터로 잘 받음 
mat1

array([[-1.01781937,  1.67579454,  0.21424901],
       [-0.39714738, -0.0481393 ,  0.5553698 ],
       [ 0.69370464, -0.25458863,  0.45209047],
       [ 2.47256353, -0.94194037,  0.28823428],
       [-1.52568189,  0.0603852 ,  0.03149339]])

In [3]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[1.01781937, 1.67579454, 0.21424901],
       [0.39714738, 0.0481393 , 0.5553698 ],
       [0.69370464, 0.25458863, 0.45209047],
       [2.47256353, 0.94194037, 0.28823428],
       [1.52568189, 0.0603852 , 0.03149339]])

In [4]:
# mat1의 제곱근 구하기 
# 음수는 제곱근이 허수이기때문에 runtimewarning 이 뜬다.
np.sqrt(mat1)

<ipython-input-4-5f34006462b6>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(mat1)


array([[       nan, 1.29452483, 0.4628704 ],
       [       nan,        nan, 0.74523137],
       [0.83288933,        nan, 0.67237673],
       [1.57243872,        nan, 0.53687455],
       [       nan, 0.245734  , 0.17746378]])

In [7]:
# 그냥 하고 싶다면?
comp1 = np.array(mat1, dtype=complex)
comp1

array([[-1.01781937+0.j,  1.67579454+0.j,  0.21424901+0.j],
       [-0.39714738+0.j, -0.0481393 +0.j,  0.5553698 +0.j],
       [ 0.69370464+0.j, -0.25458863+0.j,  0.45209047+0.j],
       [ 2.47256353+0.j, -0.94194037+0.j,  0.28823428+0.j],
       [-1.52568189+0.j,  0.0603852 +0.j,  0.03149339+0.j]])

In [8]:
# mat1 제곱하기
np.square(mat1)

array([[1.03595627e+00, 2.80828734e+00, 4.59026368e-02],
       [1.57726039e-01, 2.31739184e-03, 3.08435609e-01],
       [4.81226125e-01, 6.48153700e-02, 2.04385796e-01],
       [6.11357042e+00, 8.87251667e-01, 8.30790020e-02],
       [2.32770524e+00, 3.64637213e-03, 9.91833763e-04]])

In [9]:
# mat1의 지숫값 구하기
np.exp(mat1)

array([[ 0.36138212,  5.34303872,  1.23893112],
       [ 0.67223495,  0.95300103,  1.74258527],
       [ 2.00111523,  0.77523534,  1.57159413],
       [11.85279296,  0.38987061,  1.33406982],
       [ 0.21747271,  1.06224564,  1.03199456]])

In [10]:
# mat1의 자연로그 구하기
# 얘도 음수가 존재할 수 없기 떄문에 오류가 뜬다.
np.log(mat1)

<ipython-input-10-900afb1eb5e1>:2: RuntimeWarning: invalid value encountered in log
  np.log(mat1)


array([[        nan,  0.5162874 , -1.54061636],
       [        nan,         nan, -0.58812109],
       [-0.365709  ,         nan, -0.79387296],
       [ 0.90525548,         nan, -1.24398165],
       [        nan, -2.80701127, -3.45797752]])

In [11]:
# 상용로그
np.log10(mat1)

<ipython-input-11-a091af1a621d>:2: RuntimeWarning: invalid value encountered in log10
  np.log10(mat1)


array([[        nan,  0.22422077, -0.66908118],
       [        nan,         nan, -0.25541774],
       [-0.1588254 ,         nan, -0.34477465],
       [ 0.39314746,         nan, -0.54025436],
       [        nan, -1.21906951, -1.50178056]])

In [12]:
# 부호찾기
np.sign(mat1)

array([[-1.,  1.,  1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.]])

In [13]:
# 올림
np.ceil(mat1)

array([[-1.,  2.,  1.],
       [-0., -0.,  1.],
       [ 1., -0.,  1.],
       [ 3., -0.,  1.],
       [-1.,  1.,  1.]])

In [14]:
# 내림
np.floor(mat1)

array([[-2.,  1.,  0.],
       [-1., -1.,  0.],
       [ 0., -1.,  0.],
       [ 2., -1.,  0.],
       [-2.,  0.,  0.]])

In [15]:
# 존재하지 않는 값이 있는지 없는지 
np.isnan(mat1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
np.isnan(np.log(mat1))

<ipython-input-16-cb2ae9d6dc08>:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(mat1))


array([[ True, False, False],
       [ True,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [17]:
mat2 = np.random.randn(5,3)
mat2

array([[ 0.05697991, -0.41746594,  0.2244713 ],
       [ 0.27128043,  2.46363585, -1.15569289],
       [-1.06198323, -1.83644063, -0.39500423],
       [-0.00982737,  0.00477663, -0.04346195],
       [ 0.09287584,  1.09793624, -1.75465016]])

In [19]:
np.maximum(mat1, mat2)

array([[ 0.05697991,  1.67579454,  0.2244713 ],
       [ 0.27128043,  2.46363585,  0.5553698 ],
       [ 0.69370464, -0.25458863,  0.45209047],
       [ 2.47256353,  0.00477663,  0.28823428],
       [ 0.09287584,  1.09793624,  0.03149339]])

# Reshaping array

In [20]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# x를 3 * 3 행렬로 변형
x1 = np.arange(1, 10).reshape(3,3)

In [24]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
x == x1 # 같다!

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [27]:
# (!,2,3)을 transpose
x2 = np.array((1,2,3)).reshape(-1, 1)
x2

array([[1],
       [2],
       [3]])

# Concatenation of arrays

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 + arr2

array([5, 7, 9])

In [30]:
np.concatenate([arr1, arr2]) # 파라미터로 리스트가 들어감

array([1, 2, 3, 4, 5, 6])

In [32]:
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])