In [1]:
import numpy as np

In [4]:
# 파이썬 리스트 선언
data = list()
type(data)

list

In [5]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
data2, type(data2)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [7]:
# 넘파이 array
arr1 = np.array(data)
arr1, type(arr1)

# ndarray = n-dimensional array이다.

(array([], dtype=float64), numpy.ndarray)

In [9]:
arr2 = np.array([1,2,3,4,5])
arr2.shape

(5,)

In [10]:
L = [[1,2,3], [4,5,6], [7,8,9]]
arr3 = np.array(L)

In [11]:
arr3.shape

(3, 3)

In [12]:
arr3.ndim # 2차원 넘파이 array

2

In [13]:
arr3.dtype

dtype('int32')

In [14]:
arr3.itemsize # 원소의 사이즈(bytes)

4

# Array Initialization

In [17]:
zero = np.zeros(5)
zero, zero.dtype # default값이 float

(array([0., 0., 0., 0., 0.]), dtype('float64'))

In [18]:
np.zeros((3,3)) # 튜플 형태로 파라미터를 넣어 주어야 함

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [20]:
# 0부터 9까지 자동으로 생성한 array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10, 100) # array생성까지 자동으로 해준다.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])